<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Images\profile.picture.jpg" />
    <Content Include="StyleSheet.css" />
  </ItemGroup>

  <ItemGroup>
    <None Include="About.aspx" />
    <None Include="Cars.csproj" />
    <None Include="Contact.aspx" />
    <None Include="HomePage.aspx" />
    <None Include="Images\car1.webp" />
    <None Include="Images\car2.webp" />
    <None Include="Images\car3.webp" />
    <None Include="Images\logo.svg" />
    <None Include="master.master" />
    <None Include="master.MasterPage" />
    <None Include="Program.cs" />
    <None Include="README.md" />
    <None Include="Registration.aspx" />
    <None Include="Services.aspx" />
  </ItemGroup>

</Project>
